name: Friends

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun -v
      - run: bun install
      - run: bun run build
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
          committer: xsaction <bot@mail.xsblog.cn>
          author: XiaoShi <i@shiyunhong.com>
          commit_message: "deploy: ${{ github.sha }}"
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
